name: javascript actions

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple JS
        uses: https://github.com/actions/hello-world-javascript-action
        with:
          who-to-greet: John
